# This config should be placed in following path:
# /root/parity/config.toml

[parity]
# Ropsten Test Network
# chain = "ropsten"

[ui]
# You will need to unlock accounts manually if Wallet is disabled.
disable = true

[rpc]
#  JSON-RPC will be listening for connections on IP 0.0.0.0.
interface = "0.0.0.0"
# Allows Cross-Origin Requests from domain '*'.
cors = %RPC_CORS%
# Only selected APIs will be exposed over this interface.
apis = ["rpc"]

[ipc]
# You won't be able to use IPC to interact with Parity.
disable = true

[dapps]
# You won't be able to access any web Dapps.
disable = true

[footprint]
# Will keep up to 1201 old state entries.
pruning_history = 1201
# If defined will never use more then 8MB for all caches. (Overrides other cache settings).
cache_size = 8
# Will keep up to 33 MB old state entries.
pruning_memory = 33

#[ws]
#  JSON-RPC will be listening for connections on IP 0.0.0.0.
#interface = "0.0.0.0"
# Only selected APIs will be exposed over this interface.
#apis = ["rpc"]

[secretstore]
# You won't be able to encrypt and decrypt secrets.
disable = true

[ipfs]
# You won't be able to hash-query blockchain data.
#disable = true