image: node:6.10

stages:
  - deploy

variables:
  LAMBDA_PATH: lambda
  LAMBDA_STRIPE_CREATE_CUSTOMER_PATH: $LAMBDA_PATH/stripe-create-customer
  LAMBDA_UPDATE_FIREBASE_USER_FROM_STRIPE_PATH: $LAMBDA_PATH/update-firebase-user-from-stripe
  LAMBDA_DIGITALOCEAN_DROPLET_CREATED_PATH: $LAMBDA_PATH/digitalocean-droplet-created
  LAMBDA_DIGITALOCEAN_CREATE_DROPLET_PATH: $LAMBDA_PATH/digitalocean-create-droplet

  DASHBOARD_PATH: website/dashboard
  DASHBOARD_BUILD_PATH: $DASHBOARD_PATH/build
  DASHBOARD_DIST_PATH: $DASHBOARD_PATH/dist
  DASHBOARD_BUCKET_NAME_DEVELOPMENT: development.dashboard.etherstellar.io
  DASHBOARD_BUCKET_NAME_PRODUCTION: dashboard.etherstellar.io

# Lambda
deploy lambda development:
  stage: deploy
  script:
    - sh $LAMBDA_PATH/deploy.sh development
  only:
    - development
  environment:
    name: development

deploy lambda production:
  stage: deploy
  script:
    - sh $LAMBDA_PATH/deploy.sh production
  only:
    - master
  environment:
    name: production

# Dashboard
deploy dashboard development:
  image: noxan/docker-node-awscli-yarn
  stage: deploy
  variables:
    DASHBOARD_BUCKET_NAME: $DASHBOARD_BUCKET_NAME_DEVELOPMENT
  script:
    - sh $DASHBOARD_BUILD_PATH/deploy.sh development
  #only:
  #  - development
  environment:
    name: development

deploy dashboard production:
  image: noxan/docker-node-awscli-yarn
  stage: deploy
  variables:
    DASHBOARD_BUCKET_NAME: $DASHBOARD_BUCKET_NAME_PRODUCTION
  script:
    - sh $DASHBOARD_BUILD_PATH/deploy.sh production
  only:
    - master
  environment:
    name: production
