image: node:6.10

stages:
  - deploy

variables:
  LAMBDA_PATH: lambda
  LAMBDA_STRIPE_CREATE_CUSTOMER_PATH: $LAMBDA_PATH/stripe-create-customer
  LAMBDA_UPDATE_FIREBASE_USER_FROM_STRIPE_PATH: $LAMBDA_PATH/update-firebase-user-from-stripe
  LAMBDA_DIGITALOCEAN_DROPLET_CREATED_PATH: $LAMBDA_PATH/digitalocean-droplet-created
  LAMBDA_DIGITALOCEAN_CREATE_DROPLET_PATH: $LAMBDA_PATH/digitalocean-create-droplet

  DASHBOARD_PATH: website/dashboard
  DASHBOARD_BUILD_PATH: $DASHBOARD_PATH/build
  DASHBOARD_DIST_PATH: $DASHBOARD_PATH/dist
  DASHBOARD_BUCKET_NAME_DEVELOPMENT: development.dashboard.etherstellar.io
  DASHBOARD_BUCKET_NAME_PRODUCTION: dashboard.etherstellar.io

  ETHERSTELLAR_IO_PATH: website/etherstellar.io
  ETHERSTELLAR_IO_BUILD_PATH: $ETHERSTELLAR_IO_PATH/build
  ETHERSTELLAR_IO_DIST_PATH: $ETHERSTELLAR_IO_PATH/dist
  ETHERSTELLAR_IO_BUCKET_NAME_DEVELOPMENT: development.etherstellar.io
  ETHERSTELLAR_IO_BUCKET_NAME_PRODUCTION: etherstellar.io

  SERVER_SCRIPTS_PATH: server-scripts

# Lambda
deploy-lambda-development:
  stage: deploy
  variables:
    ES_SERVER_SCRIPTS_ARCHIVE_ENDPOINT: $ES_SERVER_SCRIPTS_ARCHIVE_ENDPOINT_DEVELOPMENT
    ES_ENDPOINT_DROPLET_CREATED: $ES_ENDPOINT_DROPLET_CREATED_DEVELOPMENT
  script:
    - sh $LAMBDA_PATH/deploy.sh development
  only:
    - development
  environment:
    name: lambda-development

deploy-lambda-production:
  stage: deploy
  variables:
    ES_SERVER_SCRIPTS_ARCHIVE_ENDPOINT: $ES_SERVER_SCRIPTS_ARCHIVE_ENDPOINT_PRODUCTION
    ES_ENDPOINT_DROPLET_CREATED: $ES_ENDPOINT_DROPLET_CREATED_PRODUCTION
  script:
    - sh $LAMBDA_PATH/deploy.sh production
  only:
    - master
  environment:
    name: lambda-production

# Dashboard
deploy-dashboard-development:
  image: noxan/docker-node-awscli-yarn
  stage: deploy
  variables:
    DASHBOARD_BUCKET_NAME: $DASHBOARD_BUCKET_NAME_DEVELOPMENT
  script:
    - sh $DASHBOARD_BUILD_PATH/deploy.sh development
  only:
    - development
  environment:
    name: dashboard-development

deploy-dashboard-production:
  image: noxan/docker-node-awscli-yarn
  stage: deploy
  variables:
    DASHBOARD_BUCKET_NAME: $DASHBOARD_BUCKET_NAME_PRODUCTION
  script:
    - sh $DASHBOARD_BUILD_PATH/deploy.sh production
  only:
    - master
  environment:
    name: dashboard-production

# Server scripts
deploy-server-scripts-development:
  stage: deploy
  artifacts:
    paths:
      - $SERVER_SCRIPTS_PATH
  script:
    - echo "Nothing to do"
  only:
   - development
  environment:
    name: server-scripts-development

deploy-server-scripts-production:
  stage: deploy
  artifacts:
    paths:
      - $SERVER_SCRIPTS_PATH
  script:
    - echo "Nothing to do"
  only:
   - master
  environment:
    name: server-scripts-production

# Etherstellar.io
# deploy-etherstellar.io-development:
#   image: noxan/docker-node-awscli-yarn
#   stage: deploy
#   variables:
#     ETHERSTELLAR_IO_BUCKET_NAME: $ETHERSTELLAR_IO_BUCKET_NAME_DEVELOPMENT
#   script:
#     - sh $ETHERSTELLAR_IO_BUILD_PATH/deploy.sh development
#   only:
#     - development
#   environment:
#     name: etherstellar.io-development
#
# deploy-etherstellar.io-production:
#   image: noxan/docker-node-awscli-yarn
#   stage: deploy
#   variables:
#     ETHERSTELLAR_IO_BUCKET_NAME: $ETHERSTELLAR_IO_BUCKET_NAME_PRODUCTION
#   script:
#     - sh $ETHERSTELLAR_IO_BUILD_PATH/deploy.sh production
#   only:
#     - master
#   environment:
#     name: etherstellar.io-production
